name: yogurt_event_bus
description: "A new Flutter package project."
version: 0.0.1
homepage: "https://github.com/Ronbb/yogurt_packages"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_lints: ^3.0.0
  benchmark_harness: ^2.2.2
  build_runner: ^2.4.6
  freezed: ^2.4.5
  test: ^1.25.2

flutter:
