name: yogurt_event_bus
description: "Provide async or sync event bus for building complex logic. Support plugins and handler priorities"
version: 0.0.5
homepage: "https://github.com/Ronbb/yogurt_packages"

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_lints: ^4.0.0
  benchmark_harness: ^2.2.2
  build_runner: ^2.4.6
  freezed: ^2.4.5
  test: ^1.25.2

flutter:
