name: yogurt_editor
description: "A new Flutter package project."
version: 0.0.1
homepage: "https://github.com/Ronbb/yogurt_packages"

environment:
  sdk: ">=3.3.0-213.0.dev <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  yogurt_event_bus: any
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.5

flutter:
