name: yogurt_mermaid
description: "A new Flutter package project."
version: 0.0.1
homepage: "https://github.com/Ronbb/yogurt_packages"

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.12.0
  petitparser: ^6.0.2
  yogurt_editor: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
