name: yogurt_mermaid
description: "A new Flutter package project."
version: 0.0.1
homepage: "https://github.com/Ronbb/yogurt_packages"

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  petitparser: ^6.0.2
  yogurt_editor: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_lints: ^3.0.0
  freezed: ^2.4.5

flutter:
